### ISSUE TITLE
Icon for new window

### ISSUE THREAD

**Issue by vavroom** [joshsimmons/publichealthpledge.com#3]
I can't upload to the repo, so here's the icon I've used in the index.html page for the "opens in new window". You can use this, or one of your own selection :) 
![new-win](https://user-images.githubusercontent.com/29165258/197832799-7c50e53e-7e79-4576-b78e-b2705629d153.png)

**Comment by bluesomewhere** [comment]
Thank you! Went ahead and used one of the icons that came with including Font Awesome, and added <span class="sr-only">Opens in a new window</span> next to them.
