### ISSUE TITLE
Link colors and underline

### ISSUE THREAD

**Issue by vavroom** [joshsimmons/publichealthpledge.com#5]
Need to adjust link colors. Right now the blue against grey gives a 3.77:1 contrast ratio. You need a minimum of 4.5:1 - So a darker blue.

I would add an underline to the links for all states. Couple reasons to that:

1. To conform to WCAG, a non-underlined link need to have a contrast ratio of at least 3:1 between link text and surrounding text as well as a distinctive feature on hover. YOu've got the underline on hover. But you don't have 3:1 contrast between link text and surrounding text. That is typically really hard to make happen.
2. More and more people are turning off blue light, especially in the evening. This means your nice blue link becomes a shade of grey and disappears as a link.

**Comment by bluesomewhere** [comment]
Thank you! Addressed in this commit: https://github.com/joshsimmons/publichealthpledge.com/commit/9640c2fff196e38f969f3b7a09cb4187b580f0da
